In [ ]:
# Import Important Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#  Data loading
url = "https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/insurance.csv"
df = pd.read_csv(url)

In [ ]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [ ]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [ ]:
# converting text data into numeric form (Encoding)
df['sex'] = df['sex'].map({'female': 0, 'male': 1})
df['smoker'] = df['smoker'].map({'no': 0, 'yes': 1})

# Encoding for region
df['region'] = df['region'].map({'southwest': 1, 'southeast': 2, 'northwest': 3, 'northeast': 4})
df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       1  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       3  21984.47061
4   32    1  28.880         0       0       3   3866.85520

In [ ]:
# Train test split
from sklearn.model_selection import train_test_split

# 1. Split X and Y
X = df.drop(columns='charges')
y = df['charges']

# 2. Train-Test Split (80% Train, 20% Test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Total rows in original data:", X.shape[0])
print("Rows for Training:", X_train.shape[0])
print("Rows for Testing:", X_test.shape[0])

Total rows in original data: 1338
Rows for Training: 1070
Rows for Testing: 268

In [ ]:
# Model training
#1. Import Linear Regression library
from sklearn.linear_model import LinearRegression

# 2. object of model
model = LinearRegression()

# 3. Model Training
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
# Model testing
# 1.prediction
y_pred = model.predict(X_test)

# 2. R2_score for testing accuracy
from sklearn.metrics import r2_score
score = r2_score(y_test, y_pred)

print(f"R2 score of our model: {score * 100:.2f}%")

R2 score of our model: 78.33%

In [ ]:
import pickle

# Model saving
with open('insurance_model.pkl', 'wb') as file:
    pickle.dump(model, file)

In [ ]:
# 1.killing past streamlit session
!pkill streamlit

# 2. Local IP checking
!curl ipv4.icanhazip.com

# 3. Streamlit app setup
!streamlit run app.py & npx localtunnel --port 8501

35.243.166.47
⠙
Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

⠹⠸⠼⠴⠦⠧your url is: https://wise-cobras-send.loca.lt
2026-06-27 16:32:31.964 Uvicorn server started on 0.0.0.0:8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://35.243.166.47:8501

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(